deploy:
  kmesh:
    env:
      xdsAddress: istiod.istio-system.svc:15012
    image:
      repository: ghcr.io/lec-bit/kmesh
      tag: latest
    imagePullPolicy: IfNotPresent
    containers:
      kmeshDaemonArgs: "--mode=dual-engine --enable-bypass=false --enable-bpf-log=true"
    resources:
      limits:
        cpu: "1"
        memory: 800Mi
kubernetesClusterDomain: cluster.local
fullnameOverride: kmesh
