// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.17.3
// source: api/grpcdata/grpcdata.proto

package grpcdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KmeshMsgService_HandleMsg_FullMethodName = "/grpcdata.kmeshMsgService/HandleMsg"
)

// KmeshMsgServiceClient is the client API for KmeshMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KmeshMsgServiceClient interface {
	HandleMsg(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error)
}

type kmeshMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKmeshMsgServiceClient(cc grpc.ClientConnInterface) KmeshMsgServiceClient {
	return &kmeshMsgServiceClient{cc}
}

func (c *kmeshMsgServiceClient) HandleMsg(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, KmeshMsgService_HandleMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KmeshMsgServiceServer is the server API for KmeshMsgService service.
// All implementations must embed UnimplementedKmeshMsgServiceServer
// for forward compatibility.
type KmeshMsgServiceServer interface {
	HandleMsg(context.Context, *MsgRequest) (*MsgResponse, error)
	mustEmbedUnimplementedKmeshMsgServiceServer()
}

// UnimplementedKmeshMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKmeshMsgServiceServer struct{}

func (UnimplementedKmeshMsgServiceServer) HandleMsg(context.Context, *MsgRequest) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMsg not implemented")
}
func (UnimplementedKmeshMsgServiceServer) mustEmbedUnimplementedKmeshMsgServiceServer() {}
func (UnimplementedKmeshMsgServiceServer) testEmbeddedByValue()                         {}

// UnsafeKmeshMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KmeshMsgServiceServer will
// result in compilation errors.
type UnsafeKmeshMsgServiceServer interface {
	mustEmbedUnimplementedKmeshMsgServiceServer()
}

func RegisterKmeshMsgServiceServer(s grpc.ServiceRegistrar, srv KmeshMsgServiceServer) {
	// If the following call pancis, it indicates UnimplementedKmeshMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KmeshMsgService_ServiceDesc, srv)
}

func _KmeshMsgService_HandleMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmeshMsgServiceServer).HandleMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmeshMsgService_HandleMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmeshMsgServiceServer).HandleMsg(ctx, req.(*MsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KmeshMsgService_ServiceDesc is the grpc.ServiceDesc for KmeshMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KmeshMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcdata.kmeshMsgService",
	HandlerType: (*KmeshMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleMsg",
			Handler:    _KmeshMsgService_HandleMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpcdata/grpcdata.proto",
}
