// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package normal

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type KmeshKprobeBpfSock struct {
	BoundDevIf     uint32
	Family         uint32
	Type           uint32
	Protocol       uint32
	Mark           uint32
	Priority       uint32
	SrcIp4         uint32
	SrcIp6         [4]uint32
	SrcPort        uint32
	DstPort        uint16
	_              [2]byte
	DstIp4         uint32
	DstIp6         [4]uint32
	State          uint32
	RxQueueMapping int32
}

type KmeshKprobeBpfSockTuple struct {
	Ipv4 struct {
		Saddr uint32
		Daddr uint32
		Sport uint16
		Dport uint16
	}
	_ [24]byte
}

type KmeshKprobeBuf struct{ Data [40]int8 }

type KmeshKprobeManagerKey struct {
	NetnsCookie uint64
	_           [8]byte
}

type KmeshKprobeSockStorageData struct {
	ConnectNs      uint64
	Direction      uint8
	ConnectSuccess uint8
	_              [2]byte
	PidTgid        uint32
	DstSvcName     [192]int8
}

// LoadKmeshKprobe returns the embedded CollectionSpec for KmeshKprobe.
func LoadKmeshKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KmeshKprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load KmeshKprobe: %w", err)
	}

	return spec, err
}

// LoadKmeshKprobeObjects loads KmeshKprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KmeshKprobeObjects
//	*KmeshKprobePrograms
//	*KmeshKprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKmeshKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKmeshKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KmeshKprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshKprobeSpecs struct {
	KmeshKprobeProgramSpecs
	KmeshKprobeMapSpecs
	KmeshKprobeVariableSpecs
}

// KmeshKprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshKprobeProgramSpecs struct {
	BpfTcpRecvmsg *ebpf.ProgramSpec `ebpf:"bpf_tcp_recvmsg"`
	BpfTcpSendmsg *ebpf.ProgramSpec `ebpf:"bpf_tcp_sendmsg"`
}

// KmeshKprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshKprobeMapSpecs struct {
	KmLogEvent     *ebpf.MapSpec `ebpf:"km_log_event"`
	KmManage       *ebpf.MapSpec `ebpf:"km_manage"`
	KmOrigDst      *ebpf.MapSpec `ebpf:"km_orig_dst"`
	KmPidDst       *ebpf.MapSpec `ebpf:"km_pid_dst"`
	KmSockstorage  *ebpf.MapSpec `ebpf:"km_sockstorage"`
	KmTmpbuf       *ebpf.MapSpec `ebpf:"km_tmpbuf"`
	KmeshMap1600   *ebpf.MapSpec `ebpf:"kmesh_map1600"`
	KmeshMap192    *ebpf.MapSpec `ebpf:"kmesh_map192"`
	KmeshMap296    *ebpf.MapSpec `ebpf:"kmesh_map296"`
	KmeshMap64     *ebpf.MapSpec `ebpf:"kmesh_map64"`
	MapOfHttpProbe *ebpf.MapSpec `ebpf:"map_of_http_probe"`
}

// KmeshKprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshKprobeVariableSpecs struct {
	BpfLogLevel *ebpf.VariableSpec `ebpf:"bpf_log_level"`
}

// KmeshKprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshKprobeObjects struct {
	KmeshKprobePrograms
	KmeshKprobeMaps
	KmeshKprobeVariables
}

func (o *KmeshKprobeObjects) Close() error {
	return _KmeshKprobeClose(
		&o.KmeshKprobePrograms,
		&o.KmeshKprobeMaps,
	)
}

// KmeshKprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshKprobeMaps struct {
	KmLogEvent     *ebpf.Map `ebpf:"km_log_event"`
	KmManage       *ebpf.Map `ebpf:"km_manage"`
	KmOrigDst      *ebpf.Map `ebpf:"km_orig_dst"`
	KmPidDst       *ebpf.Map `ebpf:"km_pid_dst"`
	KmSockstorage  *ebpf.Map `ebpf:"km_sockstorage"`
	KmTmpbuf       *ebpf.Map `ebpf:"km_tmpbuf"`
	KmeshMap1600   *ebpf.Map `ebpf:"kmesh_map1600"`
	KmeshMap192    *ebpf.Map `ebpf:"kmesh_map192"`
	KmeshMap296    *ebpf.Map `ebpf:"kmesh_map296"`
	KmeshMap64     *ebpf.Map `ebpf:"kmesh_map64"`
	MapOfHttpProbe *ebpf.Map `ebpf:"map_of_http_probe"`
}

func (m *KmeshKprobeMaps) Close() error {
	return _KmeshKprobeClose(
		m.KmLogEvent,
		m.KmManage,
		m.KmOrigDst,
		m.KmPidDst,
		m.KmSockstorage,
		m.KmTmpbuf,
		m.KmeshMap1600,
		m.KmeshMap192,
		m.KmeshMap296,
		m.KmeshMap64,
		m.MapOfHttpProbe,
	)
}

// KmeshKprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshKprobeVariables struct {
	BpfLogLevel *ebpf.Variable `ebpf:"bpf_log_level"`
}

// KmeshKprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshKprobePrograms struct {
	BpfTcpRecvmsg *ebpf.Program `ebpf:"bpf_tcp_recvmsg"`
	BpfTcpSendmsg *ebpf.Program `ebpf:"bpf_tcp_sendmsg"`
}

func (p *KmeshKprobePrograms) Close() error {
	return _KmeshKprobeClose(
		p.BpfTcpRecvmsg,
		p.BpfTcpSendmsg,
	)
}

func _KmeshKprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kmeshkprobe_bpfeb.o
var _KmeshKprobeBytes []byte
